import os
os.system("alias python=python3")
os.system("echo 'alias python=python3' >> ~/.bash_profile")
os.system("echo 'alias python=python3' >> ~/.zshrc")
print("Pyratch Updater")
print("did you choose a systemwide installation or a user installation?")
print("1. System-wide Install")
print("2. User Install")
t = int(input())
os.system("cd " + ("~/Pyratch" if t == 2 else "/Pyratch") + " && git pull")
print("you are successfully updated to the latest version of Pyratch")
print("Now go to https://localhost:5000 to use the latest version with all the updates")
os.system("cd " + ("~/Pyratch" if t == 2 else "/Pyratch") + " && python interface.py")
